### ISSUE TITLE
Yanlış ilceler

### ISSUE THREAD

**Issue by muratataman** [canbax/namaz-vakti-api#17]
https://namaz-vakti.vercel.app/api/cities?country=Turkey&region=Trabzon

İlçeler yanlış

**Comment by muratataman** [comment]
Ayrıca alfabetik gelmiyorlar
Birçok ilçe yanlış

**Comment by canbax** [comment]
değerli geri bildirimleriniz için çok teşekküler. Veriler düzeltildi. Saygılarımla
