### ISSUE TITLE
Vakitler dogru deyil?

### ISSUE THREAD

**Issue by hruzgar** [canbax/namaz-vakti-api#18]
Ilk tesekkür etmek istiyorum. Cok güzel bir proje. Gelistirmecilere destek vermek istemeyen diyanetten kurtulmak icin güzel bir cözüm olabilir.. ama maalesef benim denemde yanlis vakitleri gösteriyor.
Almanya/Münich icin baktim..
***
![2023-03-21_21-56-25](https://user-images.githubusercontent.com/84530266/226738960-f8e15249-a604-4fcc-bcc9-6ecd85149e31.png)
![2023-03-21_21-56-38](https://user-images.githubusercontent.com/84530266/226738988-19c20e50-59a4-4548-bc57-0b0f488113e7.png)
***
Acaba ben mi yanlislik yaptim bilmiyorum ama vakitler arasinda cok fark var. Tam diyanet vakitlerini kapsayacak bir sekilde olsa cidden efsane bir proje olur. Gereken yardimi ben de vermeye calisacagim!

**Comment by hruzgar** [comment]
Ayrica Google Maps den Münich in latitude ve longitude degerlerine de baktim ve api bunlari dogru bulmus. Yani hesap yanlis olmus yoksa Ülke\Bölge\Sehir den (latitude\longitude) bulmada hata yok.

**Comment by dayt47** [comment]
Peki vakitlerin diyanetin vakitleri ile 100% örtüşmesi mümkün mü? Ben Home Assistant ile bazı otomasyonlar yapmak isterim ama bunun için veriler 100% tutması lazım 1-2 dakika fark hatta >7 dakika fark olmasa benim için çok iyi olur. Bu mümkün mü? 
Siz verileri nereden alıyorsunuz?

**Comment by hruzgar** [comment]
> Selamlar. İlginiz için teşekkürler. Vakitler aslında doğru. Yatsı vaktinde 7 dk lık fark olmuş gerisi 1-2 dakika.
timezoneOffset parametresini Almanya'nın yerel saatine göre ayarlamalısınız
>
Hmm okay onu bilmiyordum ama 7dakkayı bırak a 1 2 dakka bile fark olsa namaz için çok önemli
> Ayrıca Diyanetin hesaplarına çok güvenmiyorum. 2023 de kutba yakın yerler için olan yatsı hesabını değiştirdiler. Verileri parsellemişler halka açmıyorlar.
>

>Peki vakitlerin diyanetin vakitleri ile 100% örtüşmesi mümkün mü? Ben Home Assistant ile bazı otomasyonlar yapmak isterim ama bunun için veriler 100% tutması lazım 1-2 dakika fark hatta >7 dakika fark olmasa benim için çok iyi olur. Bu mümkün mü?
Siz verileri nereden alıyorsunuz?
>
Namaz vakti gibi dünyaya açık olması gerek bir şeyi bu kadar gizli tutmaları cidden çok sinir verici bir şey.
Şu an gördüm diyanet ilk sefer api yı dışarıya sunmuş https://awqatsalah.diyanet.gov.tr/index.html .. ama sınırlı tabi başka ne beklemeliydim. Bir [açık kaynak Android uygulaması](https://github.com/metinkale38/prayer-times-android) buldum. Diyanetin sunucularından direk namaz vakti çekiyor anladığım kadarıyla. Bunu da diyanetin kendi uygulamalarında kullandığı api yi kullanarak yapıyor olması gerek. Biz de aslında o yolu kullanarak genele bir ücretsiz (veya sadece sunucu ücreti alarak) namaz vakti api hizmeti sunabiliriz. Bu da açık kaynak yapılamaz tabi yoksa diyanet gördüğü an bir şekilde engellemeyi çalışır eminim. Android uygulaması popüler olmadığı için henüz farkına varmamışlardır ama genele api açıp açık kaynak yaparsak kesin incelerler. neyse.. düşüncelerinizi bekliyorum

**Comment by dayt47** [comment]
metin kale abi igmg nin de verilerini kullaniyor ve sadece ona izin vermişler yoksa kamu oyuna kapalıymış igmg nin API'si. Diyanetin API yi kullanmak için de Diyanet TC vs. istiyorlar...

**Comment by canbax** [comment]
uygulama vakitleri coğrafi koordinatlarından kendisi hesaplıyor https://github.com/batoulapps/adhan-js in kaynak kodlarını kullanıyor. Ben şahsen bu uygulamaya diyanetten çok güvenirim çünkü herşeyi açık. Ayrıca Diyanet kurumunu din üzerinde yetkili otorite gibi görmek de bence sakıncalı bir zihniyet. Din Allah'ındır. Saygılarımla
