### ISSUE TITLE
Request to use Egyptian method for prayer times

### ISSUE THREAD

**Issue by tahadeveloper** [canbax/namaz-vakti-api#22]
I am writing to request that you change the calculation method for prayer times to the Egyptian General Authority of Survey (EGAS) method. I am currently using your service to get prayer times for my location in Egypt, and I find that the EGAS method is more accurate and reliable than the other methods that you offer.

The EGAS method is used by the government of Egypt to calculate prayer times for all locations within the country. It is a reliable and accurate method that takes into account the country's unique geographical features.

I would appreciate it if you could change the calculation method for prayer times to the EGAS method. I believe that this would be a better experience for all of your users who are located in Egypt.

Thank you for your time and consideration.

**Comment by canbax** [comment]
Hello Taha. We might add a new parameter for calculation method.

**Comment by canbax** [comment]
This feature is now added. You can use other calculation methods with `calculationMethod` parameter like below

https://namaz-vakti.vercel.app/api/timesFromPlace?country=Egypt&region=Al%20Qahirah&city=Cairo&days=3&timezoneOffset=180&calculationMethod=Egyptian
