### ISSUE TITLE
Servislerde hata mı var?

### ISSUE THREAD

**Issue by asuhasoft** [canbax/namaz-vakti-api#29]
Merhaba
Servisleri postman de çağırdığımda aşağıdaki hatayı alıyorum?
```
A server error has occurred

FUNCTION_INVOCATION_FAILED
```

**Comment by canbax** [comment]
adres değişti https://vakit.vercel.app/ Gelecekte yine güncellemeler yapacağız ama inşallah adres ve API  değişmeyecek
