### ISSUE TITLE
diyanetin sitesi değiştiğinden API bozulmuş

### ISSUE THREAD

**Issue by canbax** [canbax/namaz-vakti-api#7]
- öncelikle yeni API ile uyumlu hale getirilmeli
- Her yeni kodda ve günlük 1 kere çalışan testler ile şuan API ın çalışıp çalışmadığı denetlenmeli
- Testler manuel olarak çalıştırılıp sistem durumu test edilebilir

**Comment by Chizaruu** [comment]
Bump

**Comment by melyux** [comment]
Bozulmadı da sanki scraper işlemlerini block etmişler gibi görünüyor.

> The requested URL was rejected. Please consult with your administrator

**Comment by canbax** [comment]
puppeteer ve cypress gibi araçlar ile veri çekilemediği kesinleşti. Bir süre sonra hata veriyor. adhan-js ile veriler 2-3 dk gibi farklarla Türkiye için elde ediliyor.

**Comment by melyux** [comment]
Yani Diyanet'ten veri indirmek yerine elle mi hesaplıyoruz?

**Comment by canbax** [comment]
Evet şuan coğrafi koordinatlardan hesaplıyor
